name: Deploy To GAE On Merge To Develop
'on':
  push:
    branches:
      - develop
jobs:
  dev_build_and_deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - id: 'checkout'
        name: Checkout Repo
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate To Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.DEV_STG_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DEV_STG_WIP_SA }}
      - id: 'deploy'
        name: 'Deploy To Google Cloud App Engine'
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          flags: --no-cache
          deliverables: ./app.yaml
          env_vars: |-
            DB_NAME=${{ secrets.DEV_STG_DB_NAME }}
            DB_PASS=${{ secrets.DEV_STG_DB_PASS }}
            DB_USER=${{ secrets.DEV_STG_DB_USER }}
      - id: 'test'
        name: 'Deploy To URL'
        run: 'curl "${{ steps.deploy.outputs.url }}"'